version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: cli-table
    versions:
    - 0.3.4
    - 0.3.5
